### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by artel1992** [IgorRidanovic/DaVinciResolve-PageSwitcher#2]
I cannot import pyqt. Can you help?

**Comment by IgorRidanovic** [comment]
PyQt4 is a non-standard package. Have you installed it and you can't import PyQt4?

**Comment by artel1992** [comment]
How do I install it?  Globally? I don't know where the virtual environment is in which the script is run.  And I don't know how to install libraries there.  Pythonpath do I need this path?

**Comment by IgorRidanovic** [comment]
You can install it in the virtual environment or in the non-virtual path. I don't think there is a concept of "global" installation in any of the supported OS-es because you can have as many different versions of Python runtime installed independently as you want. One way to find out which python you're using is by executing `which python`. 

PyQt4 is no longer maintained. I think you'd install with `pip install PyQt4` if it's still available. You can try PyQt5 or PySide2 but they are not straight dropin replacements. As far as $PYTONPATH, yes it's generally relevant, but I can't advise you on your system setup.

**Comment by artel1992** [comment]
> You can install it in the virtual environment or in the non-virtual path. I don't think there is a concept of "global" installation in any of the supported OS-es because you can have as many different versions of Python runtime installed independently as you want. One way to find out which python you're using is by executing `which python`.
> 
> PyQt4 is no longer maintained. I think you'd install with `pip install PyQt4` if it's still available. You can try PyQt5 or PySide2 but they are not straight dropin replacements. As far as $PYTONPATH, yes it's generally relevant, but I can't advise you on your system setup.

It works thanks
